version: "3"
networks:
  docker-network:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: nginx
    volumes:
    - ./www:/var/www/
    - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80

    # запуск после
    depends_on:
      - php
    networks:
      - docker-network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
    - ./www:/var/www
    - ./php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
    -  9000:9000
    env_file:
      - ./php/env/git.env
    environment:
      # Отладка CLI для любого сервер нейма
      PHP_IDE_CONFIG: "serverName=_"
    networks:
      - docker-network
    
  redis:
    image: redis
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
        - ./redis/:/var/lib/redis    
    ports:
    - 6379:6379
    networks:
      - docker-network

  postgress:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
       - ./postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=qwe123
        - POSTGRES_USER=uzver
        - POSTGRES_DB=weather
    ports:
        - 5431:5432
    networks:
        - docker-network
     
       
       
